
CREATE TABLE Users (
    User_ID NUMBER PRIMARY KEY,
    Location VARCHAR2(200),
    Age NUMBER
);


CREATE TABLE RATINGS (
    USER_ID NUMBER NOT NULL,
    ISBN VARCHAR2(50) NOT NULL,
    BOOK_RATING NUMBER,
    CONSTRAINT RATINGS_PK PRIMARY KEY (USER_ID, ISBN),
    CONSTRAINT RATINGS_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT RATINGS_FK_BOOK FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);




CREATE TABLE BOOKS (
    ISBN VARCHAR2(50) PRIMARY KEY,
    BOOK_TITLE VARCHAR2(500),
    BOOK_AUTHOR VARCHAR2(200),
    YEAR_OF_PUBLICATION NUMBER,
    PUBLISHER VARCHAR2(200),
    IMAGE_URL_S VARCHAR2(500),
    IMAGE_URL_M VARCHAR2(500),
    IMAGE_URL_L VARCHAR2(500),
    note_moyenne NUMBER,
    nb_notes NUMBER 
);


